# Generated by Django 5.2.17 on 2026-08-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('section', models.CharField(choices=[('junior', 'Junior (JSS 1–3)'), ('senior', 'Senior (SS 1–3)'), ('both', 'Junior and Senior')], default='junior', max_length=10)),
                ('option_group', models.CharField(blank=True, help_text='Subjects that share a period (e.g. CHEM/COM/CRS). Leave blank if standalone.', max_length=40)),
                ('default_periods', models.PositiveIntegerField(default=2, help_text='Typical periods per week when assigning to a class.')),
            ],
            options={
                'ordering': ['section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.CharField(blank=True, help_text='e.g. Civic (JSS 1–3) only', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('population_size', models.PositiveIntegerField(default=80)),
                ('max_generations', models.PositiveIntegerField(default=250)),
                ('crossover_prob', models.FloatField(default=0.7)),
                ('mutation_prob', models.FloatField(default=0.25)),
                ('generations_run', models.PositiveIntegerField(default=0)),
                ('best_fitness', models.FloatField(blank=True, null=True)),
                ('hard_violations', models.PositiveIntegerField(default=0)),
                ('soft_violations', models.PositiveIntegerField(default=0)),
                ('execution_seconds', models.FloatField(blank=True, null=True)),
                ('fitness_history', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, help_text='Currently published timetable')),
                ('keep_locked', models.BooleanField(default=False, help_text='This run preserved locked lessons from the previous published timetable.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('JSS1', 'JSS 1'), ('JSS2', 'JSS 2'), ('JSS3', 'JSS 3'), ('SS1', 'SS 1'), ('SS2', 'SS 2'), ('SS3', 'SS 3')], max_length=8)),
                ('arm', models.CharField(blank=True, help_text='Optional arm, e.g. A, B. Leave blank if the school has one stream per level.', max_length=8)),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['level', 'arm'],
                'unique_together': {('level', 'arm')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('period', models.PositiveIntegerField(help_text='Period number in the school day')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, max_length=40)),
                ('is_break', models.BooleanField(default=False, help_text='Break / lunch / assembly — not used for lessons.')),
            ],
            options={
                'ordering': [models.Case(models.When(day='Monday', then=0), models.When(day='Tuesday', then=1), models.When(day='Wednesday', then=2), models.When(day='Thursday', then=3), models.When(day='Friday', then=4), default=5), 'period'],
                'unique_together': {('day', 'period')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_index', models.PositiveIntegerField(default=1)),
                ('option_group', models.CharField(blank=True, max_length=40)),
                ('is_locked', models.BooleanField(default=False, help_text='Keep this lesson here when regenerating with “keep locked”.')),
                ('is_manual', models.BooleanField(default=False, help_text='Moved or swapped by a person after generation.')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timeslot')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetablerun')),
            ],
            options={
                'verbose_name_plural': 'timetable entries',
                'ordering': ['school_class__level', 'time_slot__day', 'time_slot__period', 'subject__code'],
            },
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveIntegerField(default=2)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timetable.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timetable.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='timetable.teacher')),
            ],
            options={
                'ordering': ['school_class', 'subject__name'],
                'unique_together': {('school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_scope', models.CharField(choices=[('junior', 'Junior (JSS 1–3)'), ('senior', 'Senior (SS 1–3)'), ('both', 'Junior and Senior')], default='both', help_text='Limit this assignment to junior, senior, or both.', max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='timetable.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_teach', to='timetable.teacher')),
            ],
            options={
                'verbose_name': 'teacher subject',
                'verbose_name_plural': 'teacher subjects',
                'unique_together': {('teacher', 'subject', 'section_scope')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preferred', models.BooleanField(default=True, help_text='On = preferred. Off = teacher is unavailable at this slot.')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='timetable.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_prefs', to='timetable.timeslot')),
            ],
            options={
                'verbose_name_plural': 'teacher availabilities',
                'unique_together': {('teacher', 'time_slot')},
            },
        ),
    ]
