# Generated by Django 5.2.17 on 2026-08-23 14:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(8, 30))),
                ('period_minutes', models.PositiveIntegerField(default=40)),
                ('periods_before_short_break', models.PositiveIntegerField(default=3)),
                ('short_break_minutes', models.PositiveIntegerField(default=15)),
                ('periods_before_long_break', models.PositiveIntegerField(default=2)),
                ('long_break_minutes', models.PositiveIntegerField(default=40)),
                ('periods_before_lesson_break', models.PositiveIntegerField(default=3)),
                ('lesson_break_minutes', models.PositiveIntegerField(default=20)),
                ('periods_after_lesson_break', models.PositiveIntegerField(default=2)),
                ('friday_periods', models.PositiveIntegerField(default=5, help_text='Teaching periods on Friday (Mon–Thu use the full 10).')),
                ('min_periods_weekday', models.PositiveIntegerField(default=8, help_text='Minimum teaching periods per class Mon–Thu (Sport on Wednesday counts).')),
                ('wednesday_p1_is_sport', models.BooleanField(default=True, help_text='Wednesday first period is Sport for every class.')),
                ('wednesday_activity', models.CharField(default='Sport', max_length=40)),
            ],
            options={
                'verbose_name': 'bell settings',
                'verbose_name_plural': 'bell settings',
            },
        ),
        migrations.CreateModel(
            name='SimultaneousGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('section', models.CharField(choices=[('junior', 'Junior (JSS 1–3)'), ('senior', 'Senior (SS 1–3)'), ('both', 'Junior and Senior')], default='senior', max_length=10)),
                ('periods_per_week', models.PositiveIntegerField(default=3, help_text='How many shared periods this block uses each week.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': [models.Case(models.When(day='Monday', then=0), models.When(day='Tuesday', then=1), models.When(day='Wednesday', then=2), models.When(day='Thursday', then=3), models.When(day='Friday', then=4), default=5), 'sequence']},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='option_group',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='activity_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_reserved',
            field=models.BooleanField(default=False, help_text='Blocked for a whole-school activity (Wednesday Sport).'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='kind',
            field=models.CharField(choices=[('teaching', 'Teaching period'), ('short_break', 'Short break'), ('long_break', 'Long break'), ('lesson_break', 'Lesson break'), ('reserved', 'Reserved (e.g. Sport)')], default='teaching', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='sequence',
            field=models.PositiveIntegerField(default=1, help_text='Row order including breaks'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='period',
            field=models.PositiveIntegerField(default=0, help_text='Teaching period number (1–10). 0 for breaks.'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'sequence')},
        ),
        migrations.AddField(
            model_name='subject',
            name='simultaneous_group',
            field=models.ForeignKey(blank=True, help_text='Leave empty if this subject has its own periods.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='timetable.simultaneousgroup'),
        ),
    ]
